# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    groups:
      gomod-breaking:
        update-types:
          - major
      gomod-backward-compatible:
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    groups:
      github-actions-breaking:
        update-types:
          - major
      github-actions-backward-compatible:
        update-types:
          - minor
          - patch
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
