version: 1

config:
    slack_notify: true
    slack_channel: 'architecture-ci'
    dev_branch_name: dev

jobs:
    build_docker:
        steps:
            - run:
                name: Build image
                command: make image
            - run:
                name: Tag image
                command: docker tag hashicorp/vault-k8s:0.2.0 hub.infra.tiki.services/ci/vault-k8s:0.2.0

    publish_docker:
        steps:
            - run:
                name: Push image
                command: docker push hub.infra.tiki.services/ci/vault-k8s:0.2.0


workflows:
    jenkins_pipeline:
        jobs:
            - build_docker
            - publish_docker:
                requires:
                    - build_docker
                filters:
                    branches:
                        only:
                            - master




