version: 1

config:
    slack_notify: true
    slack_channel: 'architecture-ci'
    dev_branch_name: dev

jobs:
    build_docker:
        steps:
            - build_image

    publish_docker:
        steps:
            - push_image


    deploy_production:
        steps:
            - deploy_production:
                cluster: platform
                workload: vault-k8s
                has_worker: 'no'

workflows:
    jenkins_pipeline:
        jobs:
            - build_docker
            - publish_docker:
                requires:
                    - build_docker
                filters:
                    branches:
                        only:
                            - master
                            - dev
                            - staging

            - deploy_production:
                requires:
                    - publish_docker
                filters:
                    branches:
                        only:
                            - master

