---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-test
        image: test:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
