---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: sidecar-injector
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      default_type  application/octet-stream;

      sendfile        on;
      keepalive_timeout  65;

      server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
      }
    }
